### ISSUE TITLE
Follow PEP-8

### ISSUE THREAD

**Issue by pradyunsg** [csivit/members-app-backend#3]
Ref: pep8.org

**Comment by pradyunsg** [comment]
I'll make a PR for this.

**Comment by kushagra12** [comment]
Try using pycharm infact, it autoformats it

**Comment by pradyunsg** [comment]
Well, I'm halfway done. :stuck_out_tongue_winking_eye:

**Comment by palashgo** [comment]
I didnt use any ide .
Downloading PyCharm, though I don't plan to use strict pep-8 I l still try to format it better

**Comment by kushagra12** [comment]
No issues.. PyCharm will take care of all the formatting

**Comment by pradyunsg** [comment]
PR incoming.

**Comment by pradyunsg** [comment]
Resolved in #5

**Comment by pradyunsg** [comment]
@palashgo Please read PEP-8 and follow it.
