### ISSUE TITLE
Link to the API documentation in the README

### ISSUE THREAD

**Issue by pradyunsg** [csivit/members-app-backend#4]

**Comment by kushagra12** [comment]
There is an option to link it in apiary itself.

![image](https://cloud.githubusercontent.com/assets/446695/22545824/52405928-e960-11e6-8626-33729219ef47.png)

**Comment by palashgo** [comment]
But @csivit will need to grant access 
I l just drop a link in readme

**Comment by kushagra12** [comment]
I just gave it access, try linking it now

**Comment by palashgo** [comment]
Done
